### PR TITLE
[SR-1417] Add non-optional overloads of XCTAssertEqual and XCTAssertN…

### PR DESCRIPTION
**Pull request by nsalmoria**
…otEqual

Previously, the only version of the functions that accepted values was the one that implicitly wraps them into Optionals. This generated a confusing error message when the assert failed. Having a separate overload that accepts non-optional types ensures that the correct description is printed when the assert fails.

Example:
`XCTAssertEqual(1, 2, "message", file: "test.swift")`

Previous error:
`XCTAssertEqual failed: ("Optional(1)") is not equal to ("Optional(2)") - message`

New error:
`XCTAssertEqual failed: ("1") is not equal to ("2") - message`

### CODE REVIEW

**Comment by modocache** [comment]
Awesome, thanks for trying your hand at [SR-1417](https://bugs.swift.org/browse/SR-1417), @nsalmoria! 💯 

It looks like [Apple XCTest's SDK overlay](https://github.com/apple/swift/blob/354f6ea842783d3c43f76324276ecb2efd0e8c0a/stdlib/public/SDK/XCTest/XCTest.swift) doesn't have overloads of `XCTAssertEqual` for optionals. To add these overloads to swift-corelibs-xctest, we'd need to add them to Apple XCTest as well. In fact, Apple XCTest has exactly the problem you describe in [SR-1417](https://bugs.swift.org/browse/SR-1417):

```swift
// Using Apple XCTest (Xcode 7.3.1), this produces the output:
// "XCTAssertEqual failed: ("Optional(1)") is not equal to ("Optional(2)") - "
XCTAssertEqual(1, 2)
```

Could you try adding these overloads, as well as tests for them, to the Apple XCTest SDK overlay in the apple/swift repository? You can add a test to the [existing tests here](https://github.com/apple/swift/blob/354f6ea842783d3c43f76324276ecb2efd0e8c0a/validation-test/stdlib/XCTest.swift).

Sorry for the additional work. The good news is that you can improve this output for all users of XCTest, even users of Apple XCTest on OS X! 😍

**Comment by modocache** [comment]
(Oh, and let me know if you'd rather not deal with building/testing the Swift project. If you'd like, I can take care of adding these overloads to Apple XCTest.)

**Comment by nsalmoria** [comment]
As it happens, I *am* a user of XCTest on OS X :-) I'll take a stab at it.

**Comment by modocache** [comment]
Excellent! Please tag @modocache when you send a pull request. :)

**Comment by modocache** [comment]
This is blocked by https://github.com/apple/swift/pull/2788. @mike-ferris-apple, you're probably busy with WWDC, but could you take a look at that pull request?

Once https://github.com/apple/swift/pull/2788 is merged we can ask @nsalmoria to rebase these changes, then I'll review and merge them.

**Comment by modocache** [comment]
@nsalmoria Sorry for the delay! Now that https://github.com/apple/swift/pull/2788 is merged, can you rebase these changes? The conflict is probably due to #122, which moved these files around. Sorry!

Let me know if you're not sure how to rebase or would like some help.

**Comment by nsalmoria** [comment]
@modocache I think I have rebased? Not sure if I was supposed to do things differently to avoid pulling in all the history from master :-/

**Comment by nsalmoria** [comment]
@modocache I created a new pull request #123 from a new branch to attempt fixing this mess. Closing this one.

**Pull request closed without merging**
