### PR TITLE
Updates for SE-0110 Part I

### PR DESCRIPTION
**Pull request by dduan**
For more information, see: https://github.com/apple/swift/pull/3895

### CODE REVIEW

**Comment by CodaFi** [comment]
@swift-ci please test.

**Comment by dduan** [comment]
@swift-ci please test

**Comment by CodaFi** [comment]
@swift-ci please test OS X platform.

**Comment by CodaFi** [comment]
💥

**Comment by dduan** [comment]
thank you so much @CodaFi 😄

**Pull request merged**
