### PR TITLE
test: update paths for new Foundation layout

### PR DESCRIPTION
**Pull request by compnerd**

### CODE REVIEW

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by compnerd** [comment]
@swift-ci please test Linux platform

**Comment by aciidb0mb3r** [comment]
Please test with following pull request:
https://github.com/apple/swift-package-manager/pull/2584

@swift-ci Please test Linux platform

**Comment by aciidb0mb3r** [comment]
Please test with following pull request:
https://github.com/apple/swift-package-manager/pull/2584

@swift-ci Please test Linux platform

**Comment by shahmishal** [comment]
https://github.com/apple/swift/pull/29867

@swift-ci Please test Linux platform

**Comment by shahmishal** [comment]
apple/swift#29867

@swift-ci Please test Linux platform

**Comment by shahmishal** [comment]
apple/swift#29867

@swift-ci Please test Linux platform

**Comment by shahmishal** [comment]
apple/swift#29867

@swift-ci Please test Linux platform

**Comment by compnerd** [comment]
Please test with following PRs:
apple/swift#29867

@swift-ci Please test Linux platform

**Pull request merged**
