### PR TITLE
[xcodeproj] Update for Xcode 8

### PR DESCRIPTION
**Pull request by modocache**
Apply recommended settings for Xcode 8, resulting in updates in the .xcodeproj XML:

- Update to "latest Xcode version"
- Enable Clang `-Winfinite-recursion` and suspicious move warnings
- Enable Swift whole module optimization

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please test and merge

**Comment by modocache** [comment]
@swift-ci please test

**Comment by mike-ferris-apple** [comment]
Thanks, Brian!

**Comment by modocache** [comment]
My pleasure! Looks like the tests passed, so I merged myself :)

**Comment by briancroom** [comment]
Great, thanks for this housekeeping!

**Pull request merged**
