### PR TITLE
Do not merge. This is an empty commit to kick CI.

### PR DESCRIPTION
**Pull request by modocache**
According to https://lists.swift.org/pipermail/swift-corelibs-dev/Week-of-Mon-20160704/000777.html, it appears XCTest does not currently build on CI. This is a dummy commit I'll use to kick off CI -- please do not merge this pull request.

### CODE REVIEW

**Comment by modocache** [comment]
@swift-ci please test

**Comment by modocache** [comment]
This has served its purpose -- CI appears to be healthy: https://ci.swift.org/job/swift-corelibs-xctest-PR-Linux/86/ and https://ci.swift.org/job/swift-corelibs-xctest-PR-osx/82/.

**Comment by modocache** [comment]
@swift-ci please test

**Comment by parkera** [comment]
@swift-ci please test OS X

**Comment by modocache** [comment]
@parkera I wasn't able to check out the failure on OS X before you restarted it. If you have a link, that'd be great! :)

**Comment by parkera** [comment]
Oh sorry - it was exactly the same error about not specifying a Swift version. I think this became a hard error in the latest Xcode beta.

**Comment by parkera** [comment]
I think the XCTest project needs the same changes.

**Comment by parkera** [comment]
#139

**Comment by modocache** [comment]
I merged #139. Let's try this one again.

@swift-ci please test OS X

**Comment by modocache** [comment]
Great, looks like your changes got everything passing. Thanks, @parkera!! :100:

**Comment by modocache** [comment]
@swift-ci please test

**Pull request closed without merging**
