### PR TITLE
Extract some stuff to separate files

### PR DESCRIPTION
**Pull request by briancroom**
As previously discussed.

* `_XCTestObservation` -> `XCTestInternalObservation` and new file
* `XCTestCase` async methods to new file

### CODE REVIEW

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by modocache** [comment]
@swift-ci please test

**Comment by modocache** [comment]
Swift CI appears to be a very temperamental beast. 😅 

This LGTM, I'll merge once the tests pass.

**Comment by briancroom** [comment]
Looks good to go!

**Pull request merged**
