### PR TITLE
Disable cases of uses of the -index-store-path argument

### PR DESCRIPTION
**Pull request by phausler**
This avoids the failures where Xcode would emit arguments to the swift compiler of `-index-store-path`

### CODE REVIEW

**Comment by briancroom** [comment]
Thanks @phausler. Do you know if there's a reason to prefer this build setting over `INDEX_ENABLE_DATA_STORE`?

**Comment by phausler** [comment]
I am not certain exactly any specific differences, this just solved the build failure for me

**Comment by briancroom** [comment]
@swift-ci please test and merge

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by briancroom** [comment]
@swift-ci please test

**Pull request merged**
