### PR TITLE
OpenBSD support.

### PR DESCRIPTION
**Pull request by 3405691582**
x86_64 is spelled "amd64" on this platform. Return "amd64", for
consistency with Swift and other projects.

### CODE REVIEW

**Comment by spevans** [comment]
@swift-ci test

**Comment by 3405691582** [comment]
Failure seems unrelated, not sure if it's a simple test flake though.

**Comment by spevans** [comment]
@swift-ci test macos

**Comment by spevans** [comment]
@swift-ci test

**Comment by 3405691582** [comment]
Looks like these tests have failed previously due to unrelated failures. Please retry? Thanks!

**Comment by spevans** [comment]
@swift-ci test

**Comment by 3405691582** [comment]
Looks like tests have passed. Can we merge? Thanks!

**Comment by briancroom** [comment]
Hey! I'm not very familiar with how this aspect of the build works, so just a couple of questions :) You mentioned this was intended to follow the same pattern used for building the Swift compiler, right? Can you point me to an example?

I see this bit: https://github.com/apple/swift/blob/main/CMakeLists.txt#L653

But it doesn't seem to include a `amd64` case like is being added here. Are you using a local environment of your own to verify this change?

**Comment by 3405691582** [comment]
See e.g.
* https://github.com/apple/swift-corelibs-foundation/commit/808e89ea4e7db8d52aafc0db40e89c5277184324
* https://github.com/apple/swift-argument-parser/commit/b936799bcaa6c2e4fbb74507109f9b18d6650de3
* https://github.com/apple/swift-corelibs-libdispatch/pull/559/commits/0d0871d6ea3fd7188e5651d84d3b010f336f6b3c (TBD)

In the Swift compiler proper, `SWIFT_HOST_VARIANT_ARCH` is set from `build-script-impl` (see https://github.com/apple/swift/blob/b7633a112961587880cb0c497692901ceb753a89/utils/build-script-impl#L479) and gets used instead of inferred by cmake here, but it uses the system reporting of the architecture spelling, which is `amd64`. There are other artefacts within Swift that describe this alternate spelling, e.g. https://github.com/apple/swift/blob/a07b4761b397e9d7c21e1ad200f41fe2496df290/utils/swift_build_support/swift_build_support/targets.py#L236 or https://github.com/apple/swift/blob/910a7415509d188eaf7af0546a68ccd69f38f75a/lib/Basic/Platform.cpp#L258 (and so on).

> Are you using a local environment of your own to verify this change?

Yes, this gives us a clean corelibs build and helps enable us to run e.g. the Foundation tests on this platform.

**Comment by briancroom** [comment]
Thanks for the extra background! Sounds good :)

**Pull request merged**
