### PR TITLE
Fix race condition in an async test which was triggering failures (SR-2332)

### PR DESCRIPTION
**Pull request by briancroom**
When the system running these tests is under load, the assumptions that these tests were making about dates and ordering weren't holding. This could cause `test_immediatelyTrueDelayedFalsePredicateAndObject_passes` to fail intermittently, and `test_delayedTruePredicateAndObject_passes` to not be verifying the situation it was written to target.

This removes these tests' dependency on dates, increasing reliability.

Resolves: https://bugs.swift.org/browse/SR-2332

@mike-ferris-apple @parkera

### CODE REVIEW

**Comment by briancroom** [comment]
@swift-ci please test and merge

**Comment by briancroom** [comment]
@swift-ci Please test

**Comment by modocache** [comment]
Awesome, thanks @briancroom! Do you think similar changes need to be made for other similar async tests, such as [this one](https://github.com/apple/swift-corelibs-xctest/blob/32e23fbf12947c93736439a446e88a85510eb0b0/Tests/Functional/Asynchronous/Expectations/main.swift#L47-L49)?

**Comment by mike-ferris-apple** [comment]
I agree that the technique in this diff might be good to use in other places where we're relying on dates and timing to test similar stuff.

The specific test you reference seems less likely to be an issue immediately because of the different time values involved, though it does seem the same theoretical issues could be avoided with the same sort of technique.

Assuming the tests pass, though, let's get this merged.

**Comment by modocache** [comment]
Our tests seemed to have passed, so in it goes. We'll need to pick this change into `swift-3.0-branch`.

**Pull request merged**
