### PR TITLE
Cherry-picked fix for SR-2332 from master into swift-3.0-branch.

### PR DESCRIPTION
**Pull request by mike-ferris-apple**
This fix was made to master to resolve a race issue with these tests and then re-enable them. We would like to get them fixed and re-enabled in the swift-3.0-branch as well.

### CODE REVIEW

**Comment by mike-ferris-apple** [comment]
@swift-ci please test

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by shahmishal** [comment]
@swift-ci Please test Linux

**Comment by briancroom** [comment]
Looks like we're good here. Thanks all!

**Pull request merged**
