### PR TITLE
[SE-0046] Implemented consistent function labels

### PR DESCRIPTION
**Pull request by harlanhaskins**
Implemented changes specified in [SE-0046 Establish consistent label behavior across all parameters including first labels](https://github.com/apple/swift-evolution/blob/master/proposals/0046-first-label.md)

### CODE REVIEW

**Comment by briancroom** [comment]
Cool! Thanks for making these changes @harlanhaskins. For reference, the compiler work connected to this is happening in https://github.com/apple/swift/pull/2047

Depending on how quickly you're hoping to get this all in, it may make sense to wait on this until #86 and/or #88 get merged, which I expect to happen very soon.

**Comment by harlanhaskins** [comment]
We're hoping to land these changes this week, if possible.

**Comment by modocache** [comment]
I wouldn't mind merging #86 and #88 tonight. @harlanhaskins, are you capable of triggering Apple CI? 😉

**Comment by mike-ferris-apple** [comment]
This generally looks good to me. We should at least preserve the current API until we're ready to have the discussion of what other changes may be warranted (in both XCTests) for Swift 3.

**Comment by mike-ferris-apple** [comment]
@swift-ci please test

**Comment by harlanhaskins** [comment]
CI is going to fail for this as the parse changes haven't landed in the compiler.

**Pull request closed without merging**
