### PR TITLE
Fix an SE-0110 warning

### PR DESCRIPTION
**Pull request by slavapestov**

### CODE REVIEW

**Comment by slavapestov** [comment]
@pakera Are you the right person to review this?

**Comment by briancroom** [comment]
Thanks, @slavapestov! LGTM

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by modocache** [comment]
The macOS build has been broken for a while now, don't let that prevent you from merging :)

As for the cause of the build break: my understanding is that since corelibs-foundation doesn't build and test its `.xcodeproj` on macOS, but this project builds and tests an `.xcworkspace` that also contains the corelibs-foundation `.xcodeproj`, this project ends up silently inheriting corelibs-foundation's build failures. I can think of two solutions: (1) stop building and testing this project on macOS, or (2) start building and testing corelibs-foundation on macOS.

**Comment by CodaFi** [comment]
Hm, let's try that again.

@swift-ci please test macOS platform

**Comment by CodaFi** [comment]
@swift-ci please test macOS platform

**Comment by CodaFi** [comment]
@swift-ci please test

**Comment by briancroom** [comment]
@swift-ci please test

**Pull request merged**
