### PR TITLE
[WIP] Update for Swift-3 renaming.

### PR DESCRIPTION
**Pull request by ddunbar**
- This is a work-in-progress update to build against Foundation's swift-3 branch.

### CODE REVIEW

**Comment by parkera** [comment]
Thanks!

**Comment by parkera** [comment]
Built for me on 14.04 as well.

**Comment by parkera** [comment]
Merging this as I landed the Foundation changes.

**Comment by briancroom** [comment]
Excellent! Thanks @ddunbar & @parkera

**Pull request merged**
