### PR TITLE
Separate public-facing and library-private source files

### PR DESCRIPTION
**Pull request by briancroom**
This will make it easier to keep track of what belongs in which files, and also aid with browsing the source code for contributors trying to familiarize themselves with the project.

### CODE REVIEW

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by modocache** [comment]
Oops, sorry to have this sit for so long. Looks great, thanks! This will really ease the cognitive load when working on this stuff.

**Pull request merged**
