### PR TITLE
Support Windows ARM64 builds

### PR DESCRIPTION
**Pull request by hjyamauchi**
Handle the "ARM64" system processor type.

### CODE REVIEW

**Comment by hjyamauchi** [comment]
@compnerd

**Review by compnerd — APPROVED** [review]

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by hjyamauchi** [comment]
@swift-ci please test macOS platform

**Comment by hjyamauchi** [comment]
@compnerd Mind triggering the mac test again?

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-corelibs-foundation/pull/4886

@swift-ci please test macOS platform

**Comment by compnerd** [comment]
Please test with following PRs:
https://github.com/apple/swift-corelibs-foundation/pull/4886

@swift-ci please test macOS platform

**Comment by compnerd** [comment]
@swift-ci please test macOS platform

**Comment by compnerd** [comment]
CC: @shahmishal @stmontgomery - it seems that the failures on macOS are due to the runner and build configuration being out of sync. Can we get this change merged? It is a build only change which doesn't impact macOS.

**Review by stmontgomery — APPROVED** [review]

**Pull request merged**
