### PR TITLE
[XCTestCase] Workaround SR-1129 using public var

### PR DESCRIPTION
**Pull request by modocache**
`XCTestCase.name` works around a bug in the Linux Swift compiler ([SR-1129](https://bugs.swift.org/browse/SR-1129)) by declaring what should be a `private` variable as `public`. `XCTAllExpectations` works around the same bug by using a global variable. Unify the two by using the same workaround method: declare the expectations variable as `public`.

Besides using the same workaround, this has the added benefit of reducing the amount of global state in XCTest.

### CODE REVIEW

**Comment by mike-ferris-apple** [comment]
@swift-ci please test

**Comment by mike-ferris-apple** [comment]
This looks like a good change and worth the "public" workaround for avoiding global state.

**Comment by briancroom** [comment]
How about prefixing the property name with an underscore for now to help reinforce its intended private-ness and reduce the chance of a naming collision, since the class is intended to be subclassed?

**Comment by modocache** [comment]
@briancroom Done! Good suggestion, thanks!

**Pull request merged**
