### PR TITLE
[4.2] [SR-7615] Implement XCTWaiter and missing XCTestExpectation APIs #228

### PR DESCRIPTION
**Pull request by glbrntt**
See master PR: #228

### CODE REVIEW

**Comment by stmontgomery** [comment]
@swift-ci Please test

**Comment by kevints** [comment]
@swift-ci test 4.2

**Comment by kevints** [comment]
@swift-ci please test

**Comment by glbrntt** [comment]
@swift-ci please test

**Comment by glbrntt** [comment]
Closing as this is an API change which breaks SemVer.

**Pull request closed without merging**
