### PR TITLE
XCTestAssertNoThrow for 3.1

### PR DESCRIPTION
**Pull request by ArtSabintsev**
- Adds XCTestAssertNoThrow function
- Adds two test for testing XCTestAssertNoThrow

This has already been merged to master in #184, but I was asked by @briancroom to open a PR against the `swift-3.1-branch`.

### CODE REVIEW

**Comment by ArtSabintsev** [comment]
cc @briancroom ready for you.

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by ArtSabintsev** [comment]
@briancroom OSX seems to have crashed instantaneously

**Comment by briancroom** [comment]
@swift-ci please test OS X

**Comment by ArtSabintsev** [comment]
Same problem

**Comment by briancroom** [comment]
@shahmishal Hey Mishal..sorry to trouble you again, but the OS X PR CI seems to be having a hard time here. Could you take a look when you get a chance?

**Comment by shahmishal** [comment]
@swift-ci test OS X

**Comment by ArtSabintsev** [comment]
Looks like it's working - thanks, @shahmishal!

**Comment by ArtSabintsev** [comment]
Ah, it looks like it failed due to NSHost errors.

**Comment by ArtSabintsev** [comment]
looks like stuff was merge in, so another CI test is needed

**Comment by modocache** [comment]
@swift-ci please test

**Comment by ArtSabintsev** [comment]
@briancroom Looks like everything has passed!

**Comment by briancroom** [comment]
👌thanks @ArtSabintsev!

**Comment by ArtSabintsev** [comment]
My pleasure - thank you!

**Pull request merged**
