### PR TITLE
[xctest_checker] Remove installation script

### PR DESCRIPTION
**Pull request by modocache**
This Python module is only ever used by the XCTest functional tests, it doesn't need a Python package installation script.

I initially added this installation script because I mistakenly thought I needed it to run xctest_checker's tests. In fact they can be run like so:

```
$ python -m unittest discover -s Tests/Functional/xctest_checker
```

### CODE REVIEW

**Comment by briancroom** [comment]
:+1:

**Comment by mike-ferris-apple** [comment]
@swift-ci please test

**Comment by modocache** [comment]
Woah, Linux CI seemed to have had trouble cloning LLVM:

```
Cloning into 'llvm'...
error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: protocol error: bad pack header
/home/buildnode/jenkins/workspace/swift-corelibs-xctest-PR-Linux/swift/utils/update-checkout: command terminated with a non-zero exit status 128, aborting
Build step 'Execute shell' marked build as failure
```

/cc @shahmishal

**Comment by modocache** [comment]
@mike-ferris-apple Could you kick the tests again, please? The Linux failure appears spurious.

**Comment by parkera** [comment]
@swift-ci please test

**Comment by modocache** [comment]
The OS X failure is something I'll need to look into more. Merging--thanks @parkera!

**Pull request merged**
