### PR TITLE
Swift4: Update to use swift 4 syntax

### PR DESCRIPTION
**Pull request by spevans**
- Update Xcode project to Xcode 9 recommended settings

- Fix closure syntax

### CODE REVIEW

**Comment by briancroom** [comment]
Cool, thanks @spevans! Let's how CI likes it.

**Comment by briancroom** [comment]
@swift-ci please test

**Comment by spevans** [comment]
@briancroom Looks like it tested ok, can this be merged now?

**Comment by briancroom** [comment]
Great. Let's do it! Corelibs-Foundation is already building in Swift 4 mode, right?

**Comment by spevans** [comment]
Yes, it was fixed in https://github.com/apple/swift-corelibs-foundation/pull/1022

**Pull request merged**
