### PR TITLE
Migrating to Swift 3

### PR DESCRIPTION
**Pull request by moiseev**
Migrator handled most of it automatically.

### CODE REVIEW

**Comment by modocache** [comment]
This is awesome, thanks @moiseev! Would you mind squashing your commits into one?

@swift-ci pleas test

**Comment by modocache** [comment]
@swift-ci please test

**Comment by moiseev** [comment]
@modocache Ah... Sorry. Squashed. Rebased.

**Comment by mike-ferris-apple** [comment]
@swift-ci please test

**Comment by modocache** [comment]
The OS X CI isn't fully operational yet, so don't worry about that one. (I'm talking with @shahmishal about this, expect updates soon!)

The Linux CI appears to fail due to the Swift 3 changes. The failed job ran the following:

```
/home/buildnode/jenkins/workspace/swift-corelibs-xctest-PR-Linux/swift-corelibs-xctest/build_script.py \
    --swiftc=/home/buildnode/jenkins/workspace/swift-corelibs-xctest-PR-Linux/Ninja-ReleaseAssert/swift-linux-x86_64/bin/swiftc \
    --build-dir=/home/buildnode/jenkins/workspace/swift-corelibs-xctest-PR-Linux/Ninja-ReleaseAssert/xctest-linux-x86_64 \
    --swift-build-dir=/home/buildnode/jenkins/workspace/swift-corelibs-xctest-PR-Linux/Ninja-ReleaseAssert/swift-linux-x86_64 \
    --arch=x86_64
```

As you can see, it's using the `swiftc` built from the apple/swift master branch in order to build XCTest--so this *should* work. @moiseev, any idea why this might be happening? Should Swift 3 syntax work when compiled using apple/swift master right now?

**Comment by moiseev** [comment]
@modocache No. Swift 3 changes require a Swift 3 compiler (that is in swift-3-api-guidelines branch).

**Comment by modocache** [comment]
Aha, gotcha. OK, so we should only merge this once https://github.com/apple/swift/tree/swift-3-api-guidelines is merged into `master`?

**Comment by moiseev** [comment]
That would be the right thing to do, yes.

**Comment by modocache** [comment]
@moiseev Looking forward to having this merged in the coming days! I wonder if all the new code added in #43 is Swift 3 compliant, though... could you double-check before this is merged?

**Comment by moiseev** [comment]
I'm checking all the ports now. Will rebase the branch on top of latest master.

**Comment by modocache** [comment]
Cool! :+1:

**Comment by modocache** [comment]
> Migrator handled most of it automatically.

@moiseev Sorry to resurrect an old thread, but: where is this migrator? How can I use it?

**Pull request merged**
