### PR TITLE
[Tests] Update for Swift 3 rename.

### PR DESCRIPTION
**Pull request by ddunbar**

### CODE REVIEW

**Comment by ddunbar** [comment]
@swift-ci please test

**Comment by ddunbar** [comment]
This may not be the cleanest update, but it builds and passes tests for me locally (on 15.10).

**Comment by briancroom** [comment]
LGTM! We can see about better leveraging the adjusted APIs as appropriate once things have gone green again.

**Comment by ddunbar** [comment]
Linux test failure is the Foundation non-deterministic bug in JSON decoding (SR-1720)

**Pull request merged**
